[package]
name = "right-db"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
libsql = { workspace = true }
rusqlite = { workspace = true }
rusqlite_migration = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
chrono = { workspace = true }
tempfile = { workspace = true }
