[package]
name = "right-platform-store"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
futures = { workspace = true }
miette = { workspace = true }
right-sandbox = { path = "../right-sandbox", version = "*" }
sha2 = { workspace = true }
tempfile = { workspace = true }
tracing = { workspace = true }
walkdir = { workspace = true }
