[package]
name = "right-lifecycle"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
chrono = { workspace = true }
right-db = { path = "../right-db", version = "*" }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
right-db = { path = "../right-db", version = "*", features = ["test-support"] }
serde_json = { workspace = true }
