[package]
name = "right-lifecycle"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
chrono = { workspace = true }
rusqlite = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
right-db = { path = "../right-db", version = "*" }
